In [1]:
import numpy as np

In [2]:
num = np.array([67,44,23,15,78,99])

In [3]:
num

array([67, 44, 23, 15, 78, 99])

In [4]:
num.dtype

dtype('int64')

In [5]:
num.max()

99

In [6]:
num * 3

array([201, 132,  69,  45, 234, 297])

In [7]:
num < 30

array([False, False,  True,  True, False, False])

In [8]:
num[num<30]

array([23, 15])

In [9]:
M = np.array([[5,6,7],[2,8,7]])

In [10]:
M

array([[5, 6, 7],
       [2, 8, 7]])

In [11]:
M.diagonal()

array([5, 8])

#### Descriptive Statistics

In [13]:
num = np.array([54,23,11,56,32,67,88])

In [14]:
num.mean()

47.285714285714285

In [16]:
np.median(num)

54.0

In [17]:
from collections import Counter

In [18]:
x = np.array([0,0,1,0,1,0,0,1,1])
Counter(x)

Counter({0: 5, 1: 4})

In [19]:
num

array([54, 23, 11, 56, 32, 67, 88])

In [22]:
np.mean(abs(num - num.mean()))

21.6734693877551

In [23]:
num1 = num * 10
num1

array([540, 230, 110, 560, 320, 670, 880])

In [24]:
np.mean(abs(num1 - num1.mean()))

216.73469387755102

In [26]:
# variance
np.mean((num - num.mean()) ** 2)

615.3469387755102

In [27]:
np.var(num)

615.3469387755102

In [28]:
np.sqrt(np.mean((num - num.mean()) ** 2))

24.806187509883703

In [29]:
num.std()

24.806187509883703